name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 17
      - name: Lint Prettier
        run: yarn lint:prettier

  lint:
    name: Lint
    uses: the-guild-org/shared-config/.github/workflows/lint.yml@main
    with:
      script: yarn ci:lint
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: build / graphql v${{matrix.graphql_version}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        graphql_version: [15, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 18
      - name: Use GraphQL v${{matrix.graphql_version}}
        run: node ./scripts/match-graphql.js ${{matrix.graphql_version}}
      - name: Install Dependencies using Yarn
        run: yarn install --ignore-engines && git checkout yarn.lock
      - name: Build
        run: yarn ts:check

  unit:
    name: Unit Test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest] # remove windows to speed up the tests
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3
      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 18
      - name: Install Dependencies
        run: yarn install --ignore-engines && git checkout yarn.lock
      - name: Cache Jest
        uses: actions/cache@v3
        with:
          path: .cache/jest
          key: ${{ runner.os }}-${{matrix.node-version}}-${{matrix.graphql_version}}-jest-${{ hashFiles('yarn.lock') }}-${{ hashFiles('patches/*.patch') }}
      - name: Test
        run: yarn test
        env:
          CI: true

  core:
    name: Core Test / ${{matrix.os}} / node v${{matrix.node-version}} / graphql v${{matrix.graphql_version}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest] # remove windows to speed up the tests
        node-version: [14, 16, 17, 18]
        graphql_version: [15, 16, 'npm:@graphql-tools/graphql@0.0.1']
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3
      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: ${{ matrix.node-version }}
      - name: Use GraphQL v${{matrix.graphql_version}}
        run: node ./scripts/match-graphql.js ${{matrix.graphql_version}}
      - name: Install Dependencies
        run: yarn install --ignore-engines && git checkout yarn.lock
      - name: Cache Jest
        uses: actions/cache@v3
        with:
          path: .cache/jest
          key: ${{ runner.os }}-${{matrix.node-version}}-${{matrix.graphql_version}}-jest-${{ hashFiles('yarn.lock') }}-${{ hashFiles('patches/*.patch') }}
      - name: Test Core
        run: yarn test:core --ci
        env:
          CI: true

  test_esm:
    name: esm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 18
      - name: Build Packages
        run: yarn build
      - name: Test ESM & CJS exports integrity
        run: yarn bob check
